# Site settings
title: Paso Robles Roll-Off & Recycle
baseurl: "/paso-rolloff" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
