# Site settings
title: Paso Robles Roll-Off & Recycle
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.pasorolloff.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
